AutAndAutV10/ViewComponents/ForgotPasswordViewComponent.cs
using AutAndAutV10.Models;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Web;

namespace AutAndAutV10.ViewComponents
{
    [ViewComponent(Name = "ForgotPassword")]
    public class ForgotPasswordViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Views/Partials/ForgotPasswordRequest.cshtml", new ForgottenPasswordRequestModel());
        }
    }
}

AutAndAutV10/ViewComponents/MemberLoginViewComponent.cs
using AutAndAutV10.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutAndAutV10.ViewComponents
{
    public class MemberLoginViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Views/Partials/MemberLogin.cshtml", new LoginModel());
        }
    }
}

AutAndAutV10/ViewComponents/RegisterViewComponent.cs
using AutAndAutV10.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutAndAutV10.ViewComponents
{
    public class RegisterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Views/Partials/RegisterPartial.cshtml", new RegisterModel());
        }
    }
}

AutAndAutV10/ViewComponents/TwoFactorValidateViewComponent.cs
using AutAndAutV10.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutAndAutV10.ViewComponents
{
    public class TwoFactorValidateViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("TwoFactorValidate", new TwoFactoryValidateModel());
        }
    }
}

AutAndAutV10/Views/ContentPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject IPublishedValueFallback PublishedValueFallback
@{
	Layout = "FeaturedLayout.cshtml";
}

@section Featured
{
    <div class="home-img img">
        <img src="@Model.Root().GetProperty("image").Value(PublishedValueFallback)" />
    </div>
}

@section Body
{
    <div class="">
        <div class="">
            <div class="">

                <input type="hidden" id="PageId" value="@Model.Id"/>

                <div class="">@Model.CreateDate.ToShortDateString()</div>
                <h2>@Model.GetProperty("title").Value(PublishedValueFallback)</h2>

                <div>
                    <img src="@Model.GetProperty("image").Value(PublishedValueFallback)" class="contentpage-img" />
                </div>

                <div class="">@Html.Raw(Model.GetProperty("body").Value(PublishedValueFallback))</div>
            </div>
        </div>
    </div>

}

@section RightRail
{

}

AutAndAutV10/Views/FeaturedLayout.cshtml
@{ 
    Layout = "~/Views/Master.cshtml";
}

<div class="">
    <div class="">
        @RenderSection("Featured")
    </div>
</div>

<div class="">
    <div class="">
        <div class="">
            <div class="">
                @RenderSection("Body")
            </div>

            <div class="">
                @RenderSection("RightRail")
            </div>
        </div>
    </div>
</div>

AutAndAutV10/Views/ForgotPassword.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "Master.cshtml";
}

@await Component.InvokeAsync("ForgotPassword")

AutAndAutV10/Views/ForgotPasswordReset.cshtml
@using AutAndAutV10.Controllers
@using AutAndAutV10.Models
@inherits UmbracoViewPage<ForgottenPasswordResetModel>
@model AutAndAutV10.Models.ForgottenPasswordResetModel


<div class="login-container">
    <div class="wrapper-container">
        @using (Html.BeginUmbracoForm<MemberController>("ForgottenPasswordReset", FormMethod.Post))
        {
            <div class="login-label position">
                @Html.LabelFor(m => m.Email)
            </div>

            <div class="login-label position">
                @Html.TextBoxFor(m => m.Email, new { placeholder = "Email" })
            </div>

            <div class="login-label position">
                @Html.LabelFor(m => m.Password)
            </div>

            <div class="login-label position">
                @Html.TextBoxFor(m => m.Password, new { placeholder = "Password" })
            </div>

            <div class="login-label position">
                @Html.LabelFor(m => m.ConfirmPassword)
            </div>

            <div class="login-label position">
                @Html.TextBoxFor(m => m.ConfirmPassword, new { placeholder = "ConfirmPassword" })
            </div>

            <div class="position">
                <button name="login" type="submit">Reset Password</button>
            </div>
            @Html.ValidationSummary()
        }
    </div>
</div>

AutAndAutV10/Views/ForgotPswReset.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "Master.cshtml";
}

@await Component.InvokeAsync("ForgotPasswordReset")

AutAndAutV10/Views/Home.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject IPublishedValueFallback PublishedValueFallback
@{
	Layout = "FeaturedLayout.cshtml";
}

@section Featured
{
    <div class="home-img">
        <img src="@Model.GetProperty("image").Value(PublishedValueFallback)" class="home-img img" />
    </div>
}

@section Body
{
    <div class="">
        <div class="">
            <div class="home">
                <h2 class="home-title">@Model.GetProperty("title").Value(PublishedValueFallback)</h2>
                <div class="home-body">@Html.Raw(Model.GetProperty("body").Value(PublishedValueFallback))</div>
            </div>
            
            <div class="child-container">
                <ul>
                    @foreach (var child in Model.Root().Children.ToList())
                    {
                        if (child.IsDocumentType("contentPage"))
                        {
                            <li>
                                <div class="">
                                    <a href="@child.Url()">
                                        <img src="@child.GetProperty("image").Value(PublishedValueFallback)" class="child-img" />
                                    </a>
                                </div>

                                <div class="">
                                    <h3><a href="@child.Url()">@child.GetProperty("title").Value(PublishedValueFallback)</a></h3>
                                    <div class="">@child.CreateDate.ToShortDateString()</div>
                                    <div class="">@Html.Raw(child.GetProperty("body").Value(PublishedValueFallback))</div>
                                </div>
                                <hr />
                            </li>
                        }
                     }
                </ul>
            </div>
        </div>
    </div>
}

@section RightRail
{

}

AutAndAutV10/Views/Login.cshtml
@using Umbraco.Cms.Core.Security
@using Umbraco.Cms.Core.Services;
@using Umbraco.Cms.Web.Website.Models;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject IMemberManager _memberManager;
@{
	Layout = "Master.cshtml";
}
@if(!_memberManager.IsLoggedIn()){
	@(await Component.InvokeAsync("MemberLogin"))
}

AutAndAutV10/Views/Master.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@using Umbraco.Cms.Core.WebAssets
@inject IRuntimeMinifier runtimeMinifier
@{
	Layout = null;
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <meta name="description" content="">
    <meta name="author" content="">

    @Html.Raw(await runtimeMinifier.RenderCssHereAsync("main-css-bundle"))
    <link rel="stylesheet" href="registered-css-bundle"/>

</head>

<body class="">
    @*<div class="mobile-nav">
            <nav class="nav-bar">
                @Html.Partial("~/views/partials/navigation/topNavigation.cshtml")
            </nav>
        </div>*@
    <div>
        
        @await Html.PartialAsync("~/Views/Shared/Components/Header/Header.cshtml")
    </div>


    <main>
        @RenderBody()
    </main>

 @*<div class="">
    <div class="">
        @RenderSection("Featured")
    </div>
</div>

<div class="">
    <div class="">
        <div class="">
            <div class="">
                @RenderSection("Body")
            </div>

            <div class="">
                @RenderSection("RightRail")
            </div>
        </div>
    </div>
</div>
*@
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    <script src="@Url.Content("~/scripts/umbraco-starterkit-app.js")"></script>

</body>

</html>

AutAndAutV10/Views/Register.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = "Master.cshtml";
}
@await Component.InvokeAsync("Register")

AutAndAutV10/Views/SecurityContentPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject IPublishedValueFallback PublishedValueFallback
@{
    Layout = "FeaturedLayout.cshtml";
}

@* the fun starts here *@

@section Featured
{
    <div class="">
        <img src="@Model.GetProperty("image")" />
    </div>
}

@section Body
{
    <div class="">
        <div class="">
            <div class="">

                <input type="hidden" id="PageId" value="@Model.Id" />

                <div class="">@Model.CreateDate.ToShortDateString()</div>
                <h2>@Model.GetProperty("title").Value(PublishedValueFallback)</h2>

                <div class="">
                    <img src="@Model.GetProperty("image").Value(PublishedValueFallback)" class="" />
                </div>

                <div class="">@Html.Raw(Model.GetProperty("body").Value(PublishedValueFallback))</div>
            </div>
        </div>
    </div>

}

@section RightRail
{}

AutAndAutV10/Views/SecurityPage.cshtml
@using AutAndAutV10.TwoFactor
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject IPublishedValueFallback PublishedValueFallback
@using Umbraco.Cms.Core.Services
@using Umbraco.Cms.Web.Website.Controllers
@using Umbraco.Cms.Web.Website.Models
@{
	Layout = "FeaturedLayout.cshtml";
    var children = Model.Children.ToList();
}
@* the fun starts here *@

@section Featured
{
    <div class="home-img">
        <img src="@Model.GetProperty("image").Value(PublishedValueFallback)" class="home-img img" />
    </div>
}

@section Body
{
    <div class="">
        <div class="">
            <div class="home">
                <h2 class="home-title">@Model.GetProperty("title").Value(PublishedValueFallback)</h2>
                <div class="home-body">@Html.Raw(Model.GetProperty("body").Value(PublishedValueFallback))</div>
            </div>


            <div class="child-container">
                <ul>
                    @foreach (var child in children)
                    {
                        if (child.IsDocumentType("securityItemOfPage"))
                        {
                            <li>
                                <div class="">
                                    <a href="@child.Url()">
                                        <img src="@child.GetProperty("image").Value(PublishedValueFallback)" class="child-img" />
                                    </a>
                                </div>

                                <div class="">
                                    <h3><a href="@child.Url()">@child.GetProperty("title").Value(PublishedValueFallback)</a></h3>
                                    <div class="">@child.CreateDate.ToShortDateString()</div>
                                    <div class="">@Html.Raw(child.GetProperty("body").Value(PublishedValueFallback))</div>
                                </div>
                                <hr />
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
}

@section RightRail
{
    
}

AutAndAutV10/Views/TwoFactorValidatePage.cshtml
@{
    Layout = "~/Views/Master.cshtml";
}
@await Component.InvokeAsync("TwoFactorValidate")

AutAndAutV10/Views/TwoFactoryPage.cshtml
@using AutAndAutV10.TwoFactor;
@using Umbraco.Cms.Core.Services;
@using Umbraco.Cms.Web.Website.Controllers;
@using Umbraco.Cms.Web.Website.Models;
@inject MemberModelBuilderFactory memberModelBuilderFactory
@inject ITwoFactorLoginService twoFactorLoginService

@{
    Layout = "FeaturedLayout.cshtml";
}
@section Featured
{

}
@section Body
{
    <div class="login-container">
        <div class="wrapper-container">
            @{
                // Build a profile model to edit
                var profileModel = await memberModelBuilderFactory
                .CreateProfileModel()
                .BuildForCurrentMemberAsync();
                // Show all two factor providers
                var providerNames = twoFactorLoginService.GetAllProviderNames();
                if (providerNames.Any())
                {
                    <div asp-validation-summary="All" class="text-danger"></div>
                    foreach (var providerName in providerNames)
                    {
                        var setupData = await twoFactorLoginService.GetSetupInfoAsync(profileModel.Key, providerName);
                        if (setupData is null)
                        {
                            @using (Html.BeginUmbracoForm<UmbTwoFactorLoginController>(nameof(UmbTwoFactorLoginController.Disable)))
                            {
                                <input type="hidden" name="providerName" value="@providerName" />
                                <button type="submit">Disable @providerName</button>
                            }
                        }
                        else if (setupData is QrCodeSetupData qrCodeSetupData)
                        {
                            @using (Html.BeginUmbracoForm<UmbTwoFactorLoginController>(nameof(UmbTwoFactorLoginController.ValidateAndSaveSetup)))
                            {
                                <div class="text-align-center">
                                    <h3>Setup @providerName</h3>
                                    <img src="@qrCodeSetupData.SetupCode.QrCodeSetupImageUrl" />
                                    <p>Scan the code above with your authenticator app <br /> and enter the resulting code here to validate:</p>
                                    <input type="hidden" name="providerName" value="@providerName" />
                                    <input type="hidden" name="secret" value="@qrCodeSetupData.Secret" />
                                    <input type="text" name="code" />
                                    <button type="submit">Validate & save</button>
                                </div>
                            }
                        }
                    }
                }
            }
        </div>
    </div>
    
}


@section RightRail
{

}